# k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-githubflow
  labels:
    app: app-githubflow
  annotations:
    # ← ESTA ANOTACIÓN HACE QUE RELOADER REINICIE LOS PODS CUANDO CAMBIE app-config
    reloader.stakater.com/match: "true"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-githubflow
  template:
    metadata:
      labels:
        app: app-githubflow
      # ← Esta anotación es OPCIONAL pero ayuda a Reloader
      annotations:
        reloader.stakater.com/search: "true"
    spec:
      containers:
      - name: app
        image: wendyfu19/app-githubflow:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: app-config
        imagePullPolicy: Always