apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-githubflow
  labels:
    app: app-githubflow
  annotations:
    reloader.stakater.com/match: "true"  # ‚Üê ESTO ACTIVA EL REINICIO AUTO PARA CONFIGMAPS
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-githubflow
  template:
    metadata:
      labels:
        app: app-githubflow
    spec:
      containers:
      - name: app
        image: wendyfu19/app-githubflow:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: app-config
        imagePullPolicy: Always