apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress-canary
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "50" # 10% tr√°fico al canary
spec:
  rules:
  - host: vps-c1bf8222.vps.ovh.ca
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-githubflow-service-canary
            port:
              number: 3000
