apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: app-githubflow-rollout
  namespace: production
spec:
  replicas: 5
  selector:
    matchLabels:
      app: app-githubflow
  template:
    metadata:
      labels:
        app: app-githubflow
    spec:
      containers:
      - name: app
        image: wendyfu19/app-githubflow:latest   # ← tu usuario de Docker Hub
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: app-config
  strategy:
    canary:
      stableService: app-githubflow-service
      canaryService: app-githubflow-canary
      steps:
      - setWeight: 10
      - pause: { duration: 30s }
      - setWeight: 30
      - pause: { duration: 60s }
      - setWeight: 50
      - pause: {}                       # ← Aquí se detiene y espera que tú digas "continuar"
      - setWeight: 100