apiVersion: v1
kind: Service
metadata:
  name: app-githubflow-service
spec:
  selector:
    app: app-githubflow
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer   # o NodePort si usas Minikube