apiVersion: v1
kind: Service
metadata:
  name: app-githubflow-service
spec:
  selector:
    app: app-githubflow
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30300
  #type: NodePort  # Cambia LoadBalancer a NodePort – ¡esto lo arregla!		
