apiVersion: v1
kind: Service
metadata:
  name: app-githubflow-service
  namespace: production
spec:
  type: LoadBalancer           # Cambia a NodePort si usas Minikube / kind / microk8s
  selector:
    app: app-githubflow
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000