apiVersion: v1
kind: Service
metadata:
  name: app-githubflow-service-canary
spec:
  selector:
    app: app-githubflow-canary
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
