apiVersion: v1
kind: Service
metadata:
  name: app-githubflow-canary
  namespace: production
spec:
  selector:
    app: app-githubflow
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000